### ISSUE TITLE
Fails to download crypto-2012-002 videos

### ISSUE THREAD

**Issue by mrjefftang** [coursera-dl/coursera#167]
Class: crypto-2012-002

The request is for: https://class.coursera.org/crypto-2012-002/lecture/download.mp4?lecture_id=1

That URL expands to: https://d28rh4a8wq0iu5.cloudfront.net/stanford-crypto/recoded_videos/1.1%20%5Bdba8062f%5D%20.mp4?response-content-type=application%2Foctet-stream&response-content-disposition=attachment%3B%20filename%3D%221%20-%201%20-%20Course%20Overview%20%2811%20min%29.mp4%22

But the real video is: http://d2bk0s8yylvsxl.cloudfront.net/stanford-crypto/recoded_videos%2F1.1%20%5Bdba8062f%5D%20.mp4

**Comment by rbrito** [comment]
Oh, thanks for closing the bug.
