### ISSUE TITLE
[problem] - new type of course

### ISSUE THREAD

**Issue by MHM5000** [coursera-dl/coursera#282]
Hi,
Apparently there are a new set of courses like `publicspeaking`
They are not under the sub-domain `class`. They are under a folder in URL... folder of `learn`.
```
https://www.coursera.org/learn/publicspeaking
```

**Comment by mxamin** [comment]
Hi, It's an *on-demand course*. see [Issue #306] (https://github.com/coursera-dl/coursera/issues/306).
