### ISSUE TITLE
[question] If I re-run a download after it finishes, does it skip already-downloaded files?

### ISSUE THREAD

**Issue by pydolan** [coursera-dl/coursera#286]
I didn't find any mention in the documentation, so if it does do this, I suggest updating the documentation with this information. If it does not, please add a command line option to skip already-downloaded files. Thanks

**Comment by azarudeen90** [comment]
Yes it does skip the already downloaded files. I guess you can close this question.

**Comment by rbrito** [comment]
Thanks @azarudeen90 for the help triaging the bug reports. It's highly appreciated!
