### ISSUE TITLE
Could not authenticate. Cannot login on accounts.coursera.org (Coursera Auth Updated?)

### ISSUE THREAD

**Issue by henrymuppet** [coursera-dl/coursera#298]
Hi, I am getting an error when trying to download courses today.

From the looks of it, Coursera might have changed their authentication setup again. I gather this from testing the other 'coursera-dl' project which is also having trouble authenticating.

System:
1. Commit: bc09ac2587
2. OS: OSX Yosemite
3. Python: 2.7.9
4. All dependencies installed and updated
5. --clear-cache flag does not fix the error

See the error below.

>my-macbook-pro:~ username$ ~/Dropbox/Apps/coursera/coursera-dl -u 'xxx@redacted.com' -p 'mypassword' --path '/Volumes/Storage/My Videos/Lectures/Coursera' \`\ls '/Volumes/Storage/My Videos/Lectures/Coursera'\`
>Downloading class: ac-003
>Starting new HTTPS connection (1): class.coursera.org
>Starting new HTTPS connection (1): accounts.coursera.org
>Could not authenticate: Cannot login on accounts.coursera.org.
>Downloading class: algo-006
>Starting new HTTPS connection (1): class.coursera.org
>Starting new HTTPS connection (1): accounts.coursera.org
>Could not authenticate: Cannot login on accounts.coursera.org.
>Downloading class: algo2-003

I have tried using cookie authentication by exporting the cookie from Firefox using Firebug and get the blow error.

>my-macbook-pro:coursera-dl username$ ./coursera-dl -u 'xxx@redacted.com' -p 'mypassword' -c '/Users/username/Dropbox/Apps/coursera/cookies.txt' friendsmoneybytes-005
>Downloading class: friendsmoneybytes-005
>/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py:109: UserWarning: cookielib bug!
>Traceback (most recent call last):
>  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py", line 71, in _really_load
>    line.split("\t")
>ValueError: need more than 6 values to unpack
>
>  _warn_unhandled_exception()
>Traceback (most recent call last):
>  File "./coursera-dl", line 6, in <module>
>    coursera_dl.main()
>  File "/Users/username/Dropbox/Apps/coursera-dl/coursera/coursera_dl.py", line 781, in main
>    if download_class(args, class_name):
>  File "/Users/username/Dropbox/Apps/coursera-dl/coursera/coursera_dl.py", line 728, in download_class
>    username=args.username, password=args.password
>  File "/Users/username/Dropbox/Apps/coursera-dl/coursera/cookies.py", line 309, in get_cookies_for_class
>    cookies = find_cookies_for_class(cookies_file, class_name)
>  File "/Users/username/Dropbox/Apps/coursera-dl/coursera/cookies.py", line 224, in find_cookies_for_class
>    cj = get_cookie_jar(cookies_file)
>  File "/Users/username/Dropbox/Apps/coursera-dl/coursera/cookies.py", line 256, in get_cookie_jar
>    cj._really_load(cookies, 'StringIO.cookies', False, False)
>  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py", line 111, in _really_load
>    (filename, line))
>cookielib.LoadError: invalid Netscape format cookies file 'StringIO.cookies': '.coursera.org\tTRUE\t/\tFALSE\t__utmc\t158142248'

**Comment by webhat** [comment]
Same issue as you, working in py3.4 not in > py3

**Comment by rbrito** [comment]
On Jan 02 2015, Daniel W. Crompton wrote:
> Same issue as you, working in py3.4 not in > py3

Thanks. I will start investigating this issue these days and (fingers
crossed) see if I arrive at any difference in behavior between Python 2 and
Python 3.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by raszpl** [comment]
almost works now, you need to delete coursera_dl_cache every single time you run the script, so only one  copy of the script can run at a time :(

**Comment by rbrito** [comment]
Thanks for everybody that tested the new version. I am closing this bug now.

**Comment by dolphin-zs** [comment]
When I use the command as follow
coursera-dl -u  username -p password -c cookies.txt coursename
But I get the following error, I wonder if somebody could help me. Thanks!

python2.7/_MozillaCookieJar.py:109: UserWarning: cookielib bug!

I don't know what's wrong, thanks for your help!

**Comment by dolphin-zs** [comment]
I found out the reason. When you get something wrong similar to me, you could try the way as I state.
I use chrome, so I use cookies.txt extension to get the cookies.txt as all of you said. 
Firstly, I chose to copy all the text and paste into a new file named "cookies.txt", and I got the error message as @henrymuppet said.
Then, I chose to click the download link and download the cookies.txt automatically, and this time I got the right cookies file.
I compared the two cookies file I got separately and concluded that token " had been substituted to token &quot; in right cookies file. So, I suggest that you should choose the automatic download link and not copy and paste.
