### ISSUE TITLE
Cannot get the lectures list correctly, "Found 0 sections and 0 lectures on this page"

### ISSUE THREAD

**Issue by fuz-woo** [coursera-dl/coursera#300]
While I fixed the error of authentication failed #298 , I got another problem with which I cannot get the lectures list correctly. The downloader logged in successfully on accounts.couresera.org and tried to download the indroduction page on https://class.coursera.org/lecture_code/lecture/index but failed with a notice that it "Found 0 sections and 0 lectures on this page".  I used the option --clear-cache according to the hints，and got the same problem.
It's outputs like this:
```
Coursera password for fuz.woo.cn@gmail.com: 
Downloading class: sna-003
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): accounts.coursera.org
Logged in on accounts.coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Found authentication cookies.
Downloaded https://class.coursera.org/sna-003/lecture/index (6590 bytes)
Found 0 sections and 0 lectures on this page
The cookies file may be invalid, please re-run with the `--clear-cache` option.
```
I test the code and find that when the downloader trys to download the indroduction page, it gets nothing but a redirect page that remind the user to "use a modern browser with JavaScript enabled to use coursera"，and the downloader parses the page and , of course, it gets none of sections on the page.

I've tried it to download different courses, and it worked well for a few of them, pgm-003, for example. but I could not find any another course that it works. Actually,  we can get [the whole correct introduction page of pgm-003](https://class.coursera.org/pgm-003/lecture/index) with any tools (wget,axel or programming) and without any authentications,  but  not for other courses. Being not familiar with authentication technologies, I am really confused.

**Comment by gvp-hemanthreddy** [comment]
I am also facing same issue for mmds-001 course. I debugged code and saw that response for 'https://class.coursera.org/mmds-001/lecture/index' is not correct. It is returning below text instead of course syllabus.

"Please use a modern browser with JavaScript enabled to use Coursera."

**Comment by yahiaelgamal** [comment]
I also tried. I had the same problem on OS X Yosemite and python 2.7. I upgraded to python 3.4 (and used pip3, don't know if it made a difference) and then all worked fine

**Comment by wanglongqi** [comment]
not working with Python 3.4.2 under Windows 7 64bit. 

    Found 0 sections and 0 lectures on this page

**Comment by rbrito** [comment]
Hi.

On Jan 03 2015, Hemanth Reddy wrote:
> I am also facing same issue for mmds-001 course. I debugged code and saw
> that response for 'https://class.coursera.org/mmds-001/lecture/index' is
> not correct. It is returning below text instead of course syllabus.
> 
> "Please use a modern browser with JavaScript enabled to use Coursera."

I saw this when I was using Python 2, while debugging my latest changes (see
my latest updates to the master branch). With Python 3.4 (and the
corresponding modules installed), everything worked fine.

I have very little time to investigate this, but I am doing what my time
constraints allow me.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/coursera-dl/coursera/issues/300#issuecomment-68595309

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
On Jan 03 2015, Yahia wrote:
> I also tried. I had the same problem on OS X Yosemite and python 2.7. I
> upgraded to python 3.4 (and used pip3, don't know if it made a difference)
> and then all worked fine

Great.

That's exactly what I see in my Debian environments (which is what I use,
and the only operating system to which I have access---no access to MacOS X,
nor to Windows).

So, now I have just pushed some logging/debugging messages to the code, to
facilitate seeing why Python 2 behaves differently from Python 3. If anybody
could make a comparison, that would be awesome.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Hi.

On Jan 03 2015, WANG Longqi wrote:
> not working with Python 3.4.2 under Windows 7 64bit. 
> 
>     Found 0 sections and 0 lectures on this page

Do you have the latest version of the master branch of our repository?
That's super important, as the latest 3 commits make the script work with
Python 3.4.

Also, you will need to clear your cookie cache (as instructed by the
messages that you get) and rerun the script.

Finally, make sure that you have all the dependencies installed with pip3.


Hope this helps,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by wanglongqi** [comment]
@rbrito Yes, fresh installed Python 3.4.2 and just pull the code from repository. All dependencies are installed using `pip3.4.exe`. The command line includes `--clear-cache`.

**Comment by wanglongqi** [comment]
@rbrito After reboot the machine the the code is working on Python 3.4.2. Unknown reason. Sorry for inconvenience caused.

**Comment by yahiaelgamal** [comment]
I will try to do that tonight.

**Comment by yahiaelgamal** [comment]
Here the output with python 2.7 
```
coursera$python coursera-dl --debug --clear-cache -n  --  statinference-010

root[authenticate_through_netrc] Trying netrc file None
root[main] Downloading class: statinference-010
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/f6/xhdx7nsj2bzdyn7tq94bfbxc0000gn/T/yahiaelgamal_coursera_dl_cache/cookies/yahiaelgamal@gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010 HTTP/1.1" 302 None
root[login] Obtaining the csrf_token: bCVVGciprYB0suzBOcax.
root[login] Forging cookie header: csrftoken=bCVVGciprYB0suzBOcax; csrf2_token_rq7PptXG=MLg2MBL7YI9y0VpxS9qQayDG.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): accounts.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/v1/login HTTP/1.1" 200 None
root[login] Logged in on accounts.coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /signin?course_id=973518&r=https%3A%2F%2Fclass.coursera.org%2Fstatinference-010%2Fauth%2Fauth_redirector%3Fsubtype%3Dnormal%26type%3Dlogin&user_action=class&topic_name=Statistical%20Inference HTTP/1.1" 200 2214
root[down_the_wabbit_hole] Following https://class.coursera.org/statinference-010/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[get_authentication_cookies] Found authentication cookies.
root[get_syllabus_url] Using index mode with page: https://class.coursera.org/statinference-010/lecture/index
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/lecture/index HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/lecture HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /signin?course_id=973518&r=https%3A%2F%2Fclass.coursera.org%2Fstatinference-010%2Flecture&user_action=class&topic_name=Statistical%20Inference HTTP/1.1" 200 None
root[get_syllabus] Downloaded https://class.coursera.org/statinference-010/lecture/index (6590 bytes)
root[parse_syllabus] Found 0 sections and 0 lectures on this page
root[parse_syllabus] The cookies file may be invalid, please re-run with the `--clear-cache` option.```
```
vs. the output with python 3.4
```
coursera$python3 coursera-dl --debug --clear-cache -n  --  statinference-010

root[authenticate_through_netrc] Trying netrc file None
root[main] Downloading class: statinference-010
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/f6/xhdx7nsj2bzdyn7tq94bfbxc0000gn/T/yahiaelgamal_coursera_dl_cache/cookies/yahiaelgamal@gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010 HTTP/1.1" 302 None
root[login] Obtaining the csrf_token: 7k6ahd4HMn8ycqPqEKi5.
root[login] Forging cookie header: csrftoken=7k6ahd4HMn8ycqPqEKi5; csrf2_token_7Arrbew7=XUqzq4BIRpJTpWA22WJcn4HA.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): accounts.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/v1/login HTTP/1.1" 200 None
root[login] Logged in on accounts.coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/class HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/ HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010 HTTP/1.1" 200 None
root[down_the_wabbit_hole] Following https://class.coursera.org/statinference-010/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[get_authentication_cookies] Found authentication cookies.
root[get_syllabus_url] Using index mode with page: https://class.coursera.org/statinference-010/lecture/index
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/lecture/index HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /statinference-010/lecture HTTP/1.1" 200 None
root[get_syllabus] Downloaded https://class.coursera.org/statinference-010/lecture/index (65687 bytes)
root[parse_syllabus] First_Week
root[parse_syllabus]   01_01_Introduction_7-05
root[parse_syllabus]     None https://class.coursera.org/statinference-010/lecture/195
root[parse_syllabus]     txt https://class.coursera.org/statinference-010/lecture/subtitles?q=195_en&format=txt
root[parse_syllabus]     srt https://class.coursera.org/statinference-010/lecture/subtitles?q=195_en&format=srt
root[parse_syllabus]     mp4 https://class.coursera.org/statinference-010/lecture/download.mp4?lecture_id=195
root[parse_syllabus]   Brief_note_on_new_materials
```

**Comment by jinrou** [comment]
don't forget remove .pyc files from python2 before you run script with python3.4

**Comment by petrkutalek** [comment]
I also face the same problem…

OS version
```
$ uname -a
Darwin Petrs-MacBook.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
```
Python version
```
$ python -V
Python 2.7.5
```
coursera-dl
```
$ ~/Applications/coursera/coursera-dl --clear-cache --debug -n -- rprog-010
root[authenticate_through_netrc] Trying netrc file None
root[main] Downloading class: rprog-010
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/qj/_rklrnjn3sbb9_wfn9mt037w0000gn/T/petr_coursera_dl_cache/cookies/[CENSORED].txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /rprog-010 HTTP/1.1" 302 None
root[login] Obtaining the csrf_token: [CENSORED].
root[login] Forging cookie header: csrftoken=[CENSORED]; csrf2_token_ypADTRyg=[CENSORED].
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): accounts.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/v1/login HTTP/1.1" 200 None
root[login] Logged in on accounts.coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /rprog-010/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /signin?course_id=973491&r=https%3A%2F%2Fclass.coursera.org%2Frprog-010%2Fauth%2Fauth_redirector%3Fsubtype%3Dnormal%26type%3Dlogin&user_action=class&topic_name=R%20Programming HTTP/1.1" 200 None
root[down_the_wabbit_hole] Following https://class.coursera.org/rprog-010/auth/auth_redirector?type=login&subtype=normal to authenticate on class.coursera.org.
root[down_the_wabbit_hole] Exiting "deep" authentication.
root[get_authentication_cookies] Found authentication cookies.
root[get_syllabus_url] Using index mode with page: https://class.coursera.org/rprog-010/lecture/index
requests.packages.urllib3.connectionpool[_make_request] "GET /rprog-010/lecture/index HTTP/1.1" 301 None
requests.packages.urllib3.connectionpool[_make_request] "GET /rprog-010/lecture HTTP/1.1" 302 None
requests.packages.urllib3.connectionpool[_make_request] "GET /signin?course_id=973491&r=https%3A%2F%2Fclass.coursera.org%2Frprog-010%2Flecture&user_action=class&topic_name=R%20Programming HTTP/1.1" 200 2214
root[get_syllabus] Downloaded https://class.coursera.org/rprog-010/lecture/index (6590 bytes)
root[parse_syllabus] Found 0 sections and 0 lectures on this page
root[parse_syllabus] The cookies file may be invalid, please re-run with the `--clear-cache` option.
```

**Comment by leoncuhk** [comment]
same issue as petrkutalek's
python 2.7.8
win8 64bit

**Comment by vishnumohanm** [comment]
Same issue
Python 3.4.2
Win7 64bit

**Comment by seanjensengrey** [comment]
Latest @ of Jan 16th 2015 works with Python 3.4 on OSX 10.9.5

Using `homebrew` intalled Python3.4 do the following

```
/usr/local/opt/python3/bin/pyvenv-3.4 dl.env
. dl.env/bin/activate
git clone https://github.com/coursera-dl/coursera.git
pushd coursera
pip install -r requirements.txt
popd
ln -s ../../../../coursera/coursera dl.env/lib/python3.4/site-packages/
ln -s ../../coursera/coursera-dl dl.env/bin/
coursera-dl -u <username> -p <password> <course>
```

**Comment by rbrito** [comment]
Hi, people.

Can you please let me know if the latest changes that I merged right now work for you in fixing this bug? I'd love to finally close this bug report.

For more information, please see my comments at https://github.com/coursera-dl/coursera/pull/305#issuecomment-70345882 if you want to help.


Thanks for all the tests and reports,

Rogério Brito.

**Comment by wanglongqi** [comment]
@rbrito The code is working on my machine.
Windows 7 64bit  Python 3.4 32bit : working.
Windows 7 64bit Python 2.7.8 64bit: working.

**Comment by rbrito** [comment]
@wanglongqi, thank you very much for the feedback!

Nice to know that things are working. I will just wait for 1 or 2 more confirmations before closing this bug.

That being said, the code is still a bit fragile (see my previous comment) and if any of you have any ideas of how to make it more robust, please send a pull request. A large community of people that want to study will appreciate your contributions!

Regards,

Rogério Brito.

**Comment by petrkutalek** [comment]
@rbrito Thanks! Works all right on OS X Mavericks, Python 2.7.5 (default requests 2.3.0 installation upgraded to 2.5.1).

```
Petrs-MacBook:R petr$ ~/Applications/coursera/coursera-dl --clear-cache -n -- rprog-010
Downloading class: rprog-010
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): accounts.coursera.org
Logged in on accounts.coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Found authentication cookies.
Downloaded https://class.coursera.org/rprog-010/lecture/index (129172 bytes)
…
```

**Comment by merico34** [comment]
Hi, as for me (python 2.7.5), it works now again: thank you so much!

**Comment by vishnumohanm** [comment]
Yeah, I think this is fixed now.

**Comment by rbrito** [comment]
Thanks for all the tests. You guys rock. I'm closing this bug now.

**Comment by leonprou** [comment]
I have the same error on OS X with python 2.7.8

**Comment by celsom3** [comment]
I'm getting this error. (I know, a year later, right?) Should I submit a new issue?
