### ISSUE TITLE
On-Demand Courses?

### ISSUE THREAD

**Issue by webhat** [coursera-dl/coursera#306]
Is somebody already implementing downloading the On-Demand courses?

Example: [Exploring Beethoven’s Piano Sonatas](https://www.coursera.org/learn/beethoven-piano-sonatas/outline)

**Comment by rbrito** [comment]
I have not had time to look at this issue (not even to know if this will be simple or hard). Any assistance is welcome, but this, currently, has low priority.

**Comment by DXist** [comment]
+1 for this feature

**Comment by rbrito** [comment]
Hi.

On Feb 23 2015, Rinat Shigapov wrote:
> +1 for this feature

Thanks for the feedback. We already have a pull request that I hope that I
will review (and possibly merge) tomorrow. Let us keep our fingers crossed
for me to have time tomorrow.


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by Jordan4Senator** [comment]
Also a +1
I'd be happy to help test or review the pull request if it helps

**Comment by rbrito** [comment]
This is closed with https://github.com/coursera-dl/coursera/commit/081979a7e0b0b5e29e7d044ff50728086602bbab thanks to @mxamin.
