### ISSUE TITLE
Downloading Error

### ISSUE THREAD

**Issue by kunal394** [coursera-dl/coursera#310]
I am using ubuntu 14.04 and I installed coursera-dl for the very first time yesterday and I have also ensured that I have all the packages required to use coursera-dl but when using the command I cant download the videos from any course of coursera.
I am attaching the command as well as the output of the command to help understand the issue in a better way.

Command:(I have .netrc file in my home folder with content:
machine coursera-dl login ************* password ********** )

$ coursera-dl -d /my/coursera/courses/ hardwaresec-001 dsp-005

Output:

$ Coursera-dl v3.1.1 (html.parser)
Credentials found in .netrc file
Logging in as 'username******'...

Course 1 of 2
* Collecting downloadable content from https://class.coursera.org/hardwaresec-001/lecture/index
* Got all downloadable content for hardwaresec-001
Traceback (most recent call last):

File "/usr/local/bin/coursera-dl", line 9, in <module>
load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()

File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 654, in main

d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)

File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 440, in download_course

os.makedirs(course_dir)

File "/usr/lib/python2.7/os.py", line 150, in makedirs

makedirs(head, mode)

File "/usr/lib/python2.7/os.py", line 150, in makedirs

makedirs(head, mode)

File "/usr/lib/python2.7/os.py", line 150, in makedirs

makedirs(head, mode)

File "/usr/lib/python2.7/os.py", line 157, in makedirs

mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/my'

I am also attaching a screenshot of the command and its output:
![coursera-dl](https://cloud.githubusercontent.com/assets/6339991/6017494/33e9dba2-abb4-11e4-9f71-f604b1284d79.png)

**Comment by mxamin** [comment]
This error is because you don't have permission to write on root directory (/), I think adding ~ to directory path will solve the problem:
$ coursera-dl -d ~/my/coursera/courses/ hardwaresec-001 dsp-005

**Comment by kunal394** [comment]
oh yeah of course. I didnt notice that.
Anyway Thanks. It works now.
