### ISSUE TITLE
Not detecting PDF files stored on Amazon CloudFront

### ISSUE THREAD

**Issue by rvernica** [coursera-dl/coursera#312]
Hi,

I am using this version:
```
commit cb89e7c012568bf7fc79f1422988b9ec836412f5
Date:   Wed Jan 28 09:37:21 2015 -0200
```

I am trying to download the PDF lecture notes for this class: https://class.coursera.org/patterndiscovery-001 I can download all the other files fine, except PDFs. The PDFs are not detected as part of the class. The PDFs are hosted on Amazon CloudFront. For example: https://d396qusza40orc.cloudfront.net/patterndiscovery/lecture_notes/Pattern_Discovery_Lecture_1.1.pdf Maybe this is the reason why it does not detect them.

Here is what I used:
```
./coursera-dl --clear-cache -u ... -p ... -f pdf patterndiscovery-001
Downloading class: patterndiscovery-001
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): accounts.coursera.org
Logged in on accounts.coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Found authentication cookies.
Downloaded https://class.coursera.org/patterndiscovery-001/lecture/index (42218 bytes)
Orientation
  Course_Introduction_00-07-07
Week_1
  1.1._A_Brief_Introduction_to_Data_Mining_00-14-46
  2.1._Pattern_Discovery_Basic_Concepts-_What_is_Pattern_Discovery_Why_is_it_Important_00-02-52
  2.2._Pattern_Discovery_Basic_Concepts-_Frequent_Patterns_and_Association_Rules_00-05-58
  2.3._Pattern_Discovery_Basic_Concepts-_Compressed_Representation-_Closed_Patterns_and_Max-Patterns_00-07-01
  3.1._Efficient_Pattern_Mining_Methods-_The_Downward_Closure_Property_of_Frequent_Patterns_00-04-25
  3.2._Efficient_Pattern_Mining_Methods-_The_Apriori_Algorithm_00-06-11
  3.3._Efficient_Pattern_Mining_Methods-_Extensions_or_Improvements_of_Apriori_00-07-32
  3.4._Efficient_Pattern_Mining_Methods-_Mining_Frequent_Patterns_by_Exploring_Vertical_Data_Format_00-03-43
  3.5._Efficient_Pattern_Mining_Methods-_FPGrowth-_A_Pattern_Growth_Approach_00-08-04
  3.6._Efficient_Pattern_Mining_Methods-_Mining_Closed_Patterns_00-03-49
Found 2 sections and 11 lectures on this page
```
No file is downloaded.

Thanks!

**Comment by justarb** [comment]
The downloader only downloads supplemental material that appears on the All Videos page. Unfortunately the staff for the Pattern Discovery in Data Mining course did not attach these documents to the All Videos page - they only appear in the weekly module pages. I am a CTA for this course and have reached out to the University of Illinois staff to try to get this issue resolved. (A similar thing happened with the Cloud Computing Concepts course, but this has now been rectified there.)

**Comment by rbrito** [comment]
Hi.

@justarb, thanks for the information. I am putting a lable on this bug accordingly. BTW, thanks for educating the staff of the courses too. I guess that with this MOOC thing everybody is still learning the best practices...

(And grabbing material from edX is way more painful than with coursera, BTW).


Thanks,

Rogério.
