### ISSUE TITLE
Did not receive csrf_token cookie

### ISSUE THREAD

**Issue by alvesjmp** [coursera-dl/coursera#318]
Hi,

I have started getting this erros for all (two) classes I have tried to download recently (after several months without downloading anything from Coursera).

I have followed all suggestions (except for the "export Netscape-style cookies" one)) from the Troubleshooting section, to no avail.

I am running Ubuntu 14.10 and the latest coursera-dl. I have run the pip command with requirements.txt, also.

Here is an example:

```
$ ~/bin/coursera-master/coursera-dl --clear-cache --debug -n -- https://class.coursera.org/logic1-002/
root[authenticate_through_netrc] Trying netrc file None
root[main] Downloading class: https://class.coursera.org/logic1-002/
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /tmp/jmalves_coursera_dl_cache/cookies/alvesjmp@yahoo.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /https://class.coursera.org/logic1-002/ HTTP/1.1" 301 None
root[main] Could not authenticate: Did not receive csrf_token cookie.
```

My .netrc file is correct -- it is the same one that used to work until a few months ago anyway.

Did I do anything wrong? Any ideas? This also happen for the algo-007 class.

Thanks!
J

**Comment by mxamin** [comment]
You have use course **URL** instead of course **NAME**, try this:
`~/bin/coursera-master/coursera-dl --clear-cache -n -- logic1-002`

**Comment by alvesjmp** [comment]
Thanks, that works!

That is interesting... I used to use the full URL, which used to work. I missed when that get got changed, I suppose.

Best,
J
