### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by Jeet1994** [coursera-dl/coursera#321]
I am on windows 7, power shell.

I have an issue downloading the "Advanced Engineering Systems in Motion: Dynamics of Three Dimensional (3D) Motion."
The url to the course is as follows : https://www.coursera.org/learn/motion-and-kinetics/outline

When I type :  .\coursera-dl -n --path=D:\course motion-and-kinetics

I get the error the the class could not be found.

![untitled](https://cloud.githubusercontent.com/assets/7398229/6842450/5e6d83d8-d3be-11e4-9f14-a031cd1fd739.png)

**Comment by mxamin** [comment]
This course is a new type of courses called *On Demand Courses*. Using `--on-demand` option will solve your problem.

**Comment by Jeet1994** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7398229/6870844/a226a378-d4c4-11e4-9175-41adfe7866a2.png)

Doesn't work.

**Comment by mxamin** [comment]
You have entered the wrong command, there shouldn't be any space in your `username`.

**Comment by rbrito** [comment]
@Jeet1994.

Your username should be your e-mail address. Also, please change your password now, as it is visible on the screenshot. Oh, and one last point: are you using the latest version? It was only lately that I integrated @mxamin, changes to support on-demand courses.

Regards.

**Comment by rbrito** [comment]
I am closing this bug now. If there are still some problems, please let us know. Oh, BTW, to prevent other problems that recently came to surface with coursera, please update your version to: https://github.com/coursera-dl/coursera/commit/46320cfec9b5e9e42fe6c7b1ca602347e3ee4420
