### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by rihbyne** [coursera-dl/coursera#324]
hello team coursera-dl,
I have grabbed the latest master branch source code and I am getting this issue when I try to download a particular course.

command -> ./coursera-dl  -u <username>  -p <password> fog-001

Downloading class: fog-001
Starting new HTTPS connection (1): class.coursera.org
/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Starting new HTTPS connection (1): www.coursera.org
/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/coursera/coursera/coursera_dl.py", line 921, in main
    result = download_class(args, class_name)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/coursera/coursera/coursera_dl.py", line 817, in download_class
    username=args.username, password=args.password
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/coursera/coursera/cookies.py", line 336, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/coursera/coursera/cookies.py", line 159, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/coursera/coursera/cookies.py", line 114, in login
    headers=headers, allow_redirects=False)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/rihanpereira/.thunderbird/on-demand-moocs/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by mxamin** [comment]
OS?

**Comment by mehaase** [comment]
Same problem here. It worked fine last week.

The URL it is requesting (in my case) is `https://class.coursera.org/ml-008//lecture/index`. I can negotiate SSLv3 just fine with this server:

    $ openssl s_client -connect class.coursera.org:443 -ssl3 -CApath /etc/ssl/certs/
    CONNECTED(00000003)
    139730140444320:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:s3_pkt.c:1262:SSL alert number 40
    139730140444320:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:598:
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 7 bytes and written 0 bytes
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : SSLv3
        Cipher    : 0000
        Session-ID: 
        Session-ID-ctx: 
        Master-Key: 
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1427477531
        Timeout   : 7200 (sec)
        Verify return code: 0 (ok)
    ---

Python 2.7.8 on Kubuntu Linux.

**Comment by mxamin** [comment]
**Coursera** will no longer supports SSLv3 because of *POODLE* vulnerability. I'll post a pull request to cover this problem, be patient.

**Comment by JiesiGuo** [comment]
Thank you. I also run into this trouble.

**Comment by rihbyne** [comment]
thanks a ton mxamin.

**Comment by rbrito** [comment]
Hi.

@mxamin sent me a pull request that (almost) worked. I have fixed it with https://github.com/coursera-dl/coursera/commit/46320cfec9b5e9e42fe6c7b1ca602347e3ee4420 and the problem should be gone now.

Please, go test, download your lectures and happy studying (if no other problems arise). :)

**Comment by Mindstormer619** [comment]
@rbrito I have the latest clone of master with 46320cf as the latest commit. I am still facing this issue.

Here's my stacktrace:

```
PS C:\Users\SIddarth\coursera_dl> .\coursera-dl -n --path=D:\SID\Course gametheory-004
Downloading class: gametheory-004
Starting new HTTPS connection (1): class.coursera.org
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obje
ct is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Starting new HTTPS connection (1): www.coursera.org
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obje
ct is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "C:\Users\SIddarth\coursera_dl\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\Users\SIddarth\coursera_dl\coursera\coursera_dl.py", line 932, in main
    result = download_class(args, class_name)
  File "C:\Users\SIddarth\coursera_dl\coursera\coursera_dl.py", line 828, in download_class
    username=args.username, password=args.password
  File "C:\Users\SIddarth\coursera_dl\coursera\cookies.py", line 339, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\Users\SIddarth\coursera_dl\coursera\cookies.py", line 169, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "C:\Users\SIddarth\coursera_dl\coursera\cookies.py", line 137, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 602, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    allow_redirects=False,
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake fa
ilure
```

This is becoming... difficult.

**Comment by rbrito** [comment]
@Mindstormer619, Yes, I was going to suggest upgrading to Python 2.7.9.

I have two questions:

* what was the pain point in upgrading Python?
* just to prevent other people having difficulties, can you please test the change that was mentioned in https://github.com/coursera-dl/coursera/issues/330#issuecomment-89707998 ?

Thanks.

**Comment by Mindstormer619** [comment]
@rbrito The pain experienced in upgrading to v2.7.9 is (almost) entirely my fault. I followed [this](http://stackoverflow.com/questions/15102943/how-to-update-python) and it did a lot of weird stuff because what I didn't realize was that I was trying to install a 32-bit upgrade MSI over a 64-bit Python 2.7.6. All sorts of not-so-hilarious uninstalling and reinstalling ensued. It's fine now though (Moral of the story: always uninstall first. Saves time and confusion in the long run.)

My downloader works properly without changing said line. The contents of line 116 are `    r = session.post(AUTH_URL_V3, data=data,`. If you want me to test it by replacing it with `AUTH_URL`, I can, but just as your [comment](https://github.com/coursera-dl/coursera/issues/330#issuecomment-89708466) said, I will not be a valuable data point either as it works even without said change.
