### ISSUE TITLE
~/.netrc access too permissive: access permissions must restrict access to only the owner

### ISSUE THREAD

**Issue by shirishag75** [coursera-dl/coursera#339]
Hi all, 
I was trying to make the path and came across this :-

    [$] python coursera-dl -n --path=/home/shirish/Videos/Coursera/Classes/ "principles-of-macroeconomics" --debug                      
    root[authenticate_through_netrc] Trying netrc file None
    root[parseArgs] Did not find valid netrc file:
    ~/.netrc access too permissive: access permissions must restrict access to only the owner (/home/shirish/.netrc, line 1)

This is where the .netrc f

    [$] ll -h ~/.netrc                                                                                                                  
    -rw-r--r-- 1 shirish shirish 77 Apr 17 07:13 /home/shirish/.netrc

This is how my .netrc looks like :-

$ cat .netrc                                                                                                                      
machine coursera-dl login "xxxxxxxx@xxx.com" password "xxx?xxxxxxxx"

I tried various combintions of login and password as in `<"username">` and `<"password">`  but neither of them worked. 

Also machine is to be generic or is it the supposed to default to host-name ?

as in :-

    [$] hostname                                                                                                                        
    debian

I am running Debian jessie and these are the various versions of packages as asked in requirements.txt :-

    $] dpkg -l python-bs4 python-requests python-six python-html5lib python-setuptools                                                 [7:29:38]
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                           Version              Architecture         Description
    +++-==============================-====================-====================-=================================================================
    ii  python-bs4                     4.3.2-2              all                  error-tolerant HTML parser for Python
    ii  python-html5lib                0.999-3              all                  HTML parser/tokenizer based on the WHATWG HTML5 specification (Py
    ii  python-requests                2.4.3-6              all                  elegant and simple HTTP library for Python2, built for human bein
    ii  python-setuptools              12.2-1               all                  Python Distutils Enhancements
    ii  python-six                     1.9.0-1              all                  Python 2 and 3 compatibility library (Python 2 interface)
    
python --version is :-

    [$] python --version                                                                                                                
    Python 2.7.9

Please let me know if something is unclear.

**Comment by vladistan** [comment]
Your .netrc is too permissive.   Use this command, to set permissions right:

chmod og-rw /home/shirish/.netrc

**Comment by shirishag75** [comment]
@vladistan it fixed the issue, it would be nice to document or at least share here as well as there what og-rw does.

**Comment by rbrito** [comment]
@shirishag75, please send a pull request with updates to the documentation. Probably in the troubleshooting part?

BTW, perhaps with a numeric way of expressing the permissions things would be clearer? Something like 600? The `og-rw` thing doesn't remove any potential executable bits that the file might have...

(For some weird reason it may have those? E.g., using a vfat filesystem on a unix system, perhaps?).

**Comment by akshayjai1** [comment]
> Your .netrc is too permissive. Use this command, to set permissions right:
> 
> chmod og-rw /home/shirish/.netrc

yes worked!
