### ISSUE TITLE
Subtitles of On demand courses are not downloaded

### ISSUE THREAD

**Issue by Ryan147** [coursera-dl/coursera#343]
Using the latest version of coursera-dl I downloaded the on-demand course: businessinsociety.

However it downloads only the mp4 file and not subtitles which are present.

**Comment by rbrito** [comment]
It would help me a little bit if you could grab the HTML file that contains the links to the videos and the subtitles and upload them somewhere so that I (or other people implementing the feature) don't have to enroll in yet another course. :)

It would be best to upload to a place where we could grab and make part of our test suite (like what we have in https://github.com/coursera-dl/coursera/tree/master/coursera/test/fixtures/html).

Regards,

Rogério Brito.

**Comment by rbrito** [comment]
Hi, @Ryan147.

Can you please test these changes and report if the problem is fixed for you? The changes were contributed by @mxamin.

It would be great if any one of you could grab and send the HTML of one of these courses, so that we can add them to our test suite.

Thanks,

Rogério.

**Comment by rbrito** [comment]
@marcofat, please see my previous message on this issue, both regarding testing the change and also regarding the HTML of one of these courses to include it in our test suite.

Thanks.

**Comment by Ryan147** [comment]
Hello Rogerio,

Just tried it out and I got the following:

Downloading class: work-smarter-not-harder
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/work-smarter-not-harder (9227 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
work-smarter-not-harder\01_smart-work-habits-just-don-t-happen\01_smart-work-habits-just-don-t-happen\01_1-1-productive-vs-unproductive-work.mp4 already downloaded
Downloading: work-smarter-not-harder\01_smart-work-habits-just-don-t-happen\01_smart-work-habits-just-don-t-happen\01_1-1-productive-vs-unproductive-work.srt
Downloading https://www.coursera.org/api/opencourse.v1/video/Gf-3xt2HEeSr3CIACy-K1g/subtitles/en?vtt=false -> work-smarter-not-harder\01_smart-work-habits-just-don-t-happen\01_smart-work-habits-just-don-t-happen\01_1-1-productive-vs-unproductive-work.srt
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 2 seconds ...
Starting new HTTPS connection (2): www.coursera.org
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 4 seconds ...
Starting new HTTPS connection (3): www.coursera.org
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 8 seconds ...
Starting new HTTPS connection (4): www.coursera.org
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 16 seconds ...
Starting new HTTPS connection (5): www.coursera.org
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 32 seconds ...
Skipping, can't download file ...
Not Found 404

**Comment by Ryan147** [comment]
Regarding the HTML file I see that it contains personal information so I am not sure whether editing that out will keep the file workable and also I'd rather not share those personal info to be put in some test case. Hope you will understand my reluctancy even though I would very much like to help out.

**Comment by rbrito** [comment]
@Ryan147, feel free to substitute your personal information with, say, XXXX or whatever. I'm really not interested in getting personal information from anybody. I already have more information than I can cope with.

BTW, I would strongly recommend that you use an external downloader like wget (or aria2c---this one is what I use myself) if you can. Our downloading abilities leave a lot to be desired, really.

**Comment by mxamin** [comment]
Sorry @rbrito, It seems that I made a huge mistake. Downloading subtitles doesn't follow by a fix URL. I'll try to fix it ASAP.

**Comment by Ryan147** [comment]
Thank you both Rogerio and MxAmin. It is working now!

**Comment by rbrito** [comment]
@Ryan147, thank you very much for testing. I ended up registering for some ondemand courses and tested this before I pushed the changes to our master branch.

I also published a new version of the script to PyPI: https://pypi.python.org/pypi/coursera
