### ISSUE TITLE
feature request: officially support coursera-dl-docker

### ISSUE THREAD

**Issue by snowch** [coursera-dl/coursera#344]
I've run into multiple issues trying to get a working coursera-dl environment.  

Then I found this:
https://registry.hub.docker.com/u/mshytikov/coursera-dl-docker/

All I needed was docker to be able to start downloading courses - so easy!

**Comment by Make42** [comment]
I have never used Docker before, so I had to figure this out the hard way - especially the part with the alias which has to be done a root/sudo environment. Here are the steps how I managed:

$ sudo apt-get update $ sudo apt-get install wget # if you haven't installed wget, which you most likely have
$ wget -qO- https://get.docker.com/ | sh
$ sudo reboot # my system required me to reboot
$ sudo docker run hello-world # to test whether docker is installed properly
$ docker pull mshytikov/coursera-dl-docker # pull the image
$ sudo su - # to get into root
$ alias coursera-dl='docker run --rm -v /tmp/coursera:/downloads mshytikov/coursera-dl-docker'
$ coursera-dl -u me@example.com -p mypassord procmin-002
