### ISSUE TITLE
cannot download srt and txt file from https://www.coursera.org/learn/... classes

### ISSUE THREAD

**Issue by marcofat** [coursera-dl/coursera#346]
Hi,
I'm using the new script recommended on issue #333 to download educational materials from courses with https://www.coursera.org/learn/... common address but I can only download video.
I would be particularly interested in dowloading also subtitles and if it's possible pdf and pptx as well.

A couple of classes are:
https://www.coursera.org/learn/competitivestrategy/outline
https://www.coursera.org/learn/advanced-competitive-strategy

**Comment by marcofat** [comment]
I realize it's a duplicate of issue #343

**Comment by rbrito** [comment]
OK. I will close this, then. Thanks.
