### ISSUE TITLE
Error w/ python3 

### ISSUE THREAD

**Issue by MJafarMashhadi** [coursera-dl/coursera#371]
I installed coursera-dl from pip on windows with 

    python -m pip install coursera-dl

Here's the output:

    Downloading/unpacking coursera-dl
      Downloading coursera-dl-3.1.1.tar.gz
      Running setup.py (path:C:\Users\mjafar\AppData\Local\Temp\pip_build_mjafar\coursera-dl\setup.py) egg_info for package
    coursera-dl

    Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in d:\program files\python34\lib\site-packages
    (from coursera-dl)
    Downloading/unpacking mechanize (from coursera-dl)
      Running setup.py (path:C:\Users\mjafar\AppData\Local\Temp\pip_build_mjafar\mechanize\setup.py) egg_info for package me
    chanize

    Downloading/unpacking argparse (from coursera-dl)
      Downloading argparse-1.3.0-py2.py3-none-any.whl
    Installing collected packages: coursera-dl, mechanize, argparse
      Running setup.py install for coursera-dl
          File "D:\Program Files\python34\Lib\site-packages\courseradownloader\courseradownloader.py", line 98
            print "Invalid week filter, should be a comma separated list of integers", e
                                                                                    ^
        SyntaxError: Missing parentheses in call to 'print'

          File "D:\Program Files\python34\Lib\site-packages\courseradownloader\util.py", line 98
            print ' Warning: Cannot trim filename "%s" to fit required path length (%d)' % (pathname, max_path_len)
                                                                                       ^
        SyntaxError: invalid syntax

        Installing coursera-dl-script.py script to D:\Program Files\python34\Scripts
        Installing coursera-dl.exe script to D:\Program Files\python34\Scripts
      Running setup.py install for mechanize
          File "D:\Program Files\python34\Lib\site-packages\mechanize\_beautifulsoup.py", line 267
            raise AttributeError, "'%s' object has no attribute '%s'" % (self.__class__.__name__, attr)
                                ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_form.py", line 196
            nonce = "".join([str(random.randint(0, sys.maxint-1)) for i in 0,1,2])
                                                                            ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_html.py", line 191
            except sgmllib.SGMLParseError, exc:
                                         ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_http.py", line 243
            except HTTPError, f:
                            ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_mechanize.py", line 231
            except urllib2.HTTPError, error:
                                    ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_msiecookiejar.py", line 33
            WIN32_EPOCH = 0x019db1ded53e8000L  # 1970 Jan 01 00:00:00 in Win32 FILETIME
                                            ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_opener.py", line 320
            except urllib2.HTTPError, error:
                                    ^
        SyntaxError: invalid syntax

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_sgmllib_copy.py", line 396
            print '*** Unbalanced </' + tag + '>'
                                    ^
        SyntaxError: Missing parentheses in call to 'print'

          File "D:\Program Files\python34\Lib\site-packages\mechanize\_urllib2_fork.py", line 173
            raise AttributeError, attr
                                ^
        SyntaxError: invalid syntax

    Successfully installed coursera-dl mechanize argparse
    Cleaning up...

And when i try to download a course i get:

    Traceback (most recent call last):
      File "D:\Program Files\python34\Scripts\coursera-dl-script.py", line 9, in <module>
        load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
      File "D:\Program Files\python34\lib\site-packages\pkg_resources.py", line 353, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "D:\Program Files\python34\lib\site-packages\pkg_resources.py", line 2302, in load_entry_point
        return ep.load()
      File "D:\Program Files\python34\lib\site-packages\pkg_resources.py", line 2029, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "D:\Program Files\python34\lib\site-packages\courseradownloader\courseradownloader.py", line 98
        print "Invalid week filter, should be a comma separated list of integers", e
                                                                                ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by rbrito** [comment]
Hi, MohammadJafar MashhadiEbrahim.

On Jun 15 2015, MohammadJafar MashhadiEbrahim wrote:
> I installed coursera-dl from pip on windows with 
> 
>     python -m pip install coursera-dl
> 
> Here's the output:
> 
>     Downloading/unpacking coursera-dl
>       Downloading coursera-dl-3.1.1.tar.gz
(...)

Unfortunately, this is not this project. It is another project that
(unfortunately) has the same name. To install our project, you use only:

    python -m pip install coursera

Note that the package does *not* have the `-dl` suffix.

Our project *does* support Python 2 and Python 3 and we have automated tests
(and a wide community of users that use the project with Python 3).  You can
see, for example, the result of our automated test results at corresponding to
the latest modifications that I made at:

    https://travis-ci.org/coursera-dl/coursera/builds/66390054

In fact, I use the project myself with Python 3.4.  I welcome you to try our
project to see if it works better for you. Our project is actively supported
and we have gathered a large community of users that are very helpful and
that are able to help each other, even when I am not present (but I usually
am).

You *may* have to uninstall the other package before trying yours, since
they both conflict in using the same *executable* name.


Hope this helps,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Oh, BTW, @MJafarMashhadi.

If you can provide any feedback regarding if our script worked for you (or even if it didn't), that would be awesome!

**Comment by MJafarMashhadi** [comment]
Oh thanks! Works like a charm!

**Comment by wunderkid** [comment]
Thanks for the advise. Worked for me too!
